"""add company relationship

Revision ID: 1ea5b0fed717
Revises: 1b4c5110a157
Create Date: 2026-08-01 16:18:35.064290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ea5b0fed717'
down_revision: Union[str, Sequence[str], None] = '1b4c5110a157'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'website',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(op.f('companies_email_key'), 'companies', type_='unique')
    op.add_column('customers', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'customers', 'companies', ['company_id'], ['id'])
    op.drop_column('customers', 'company')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('company', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'company_id')
    op.create_unique_constraint(op.f('companies_email_key'), 'companies', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('companies', 'website',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
