"""add company truly owner

Revision ID: e1b14cc95864
Revises: 9df274c2bb52
Create Date: 2026-08-10 01:28:08.788775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1b14cc95864'
down_revision: Union[str, Sequence[str], None] = '9df274c2bb52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


#def upgrade() -> None:
    #"""Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('companies', sa.Column('owner_id', sa.Integer(), nullable=False))
    #op.create_foreign_key(None, 'companies', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###

def upgrade() -> None:
    op.add_column(
        "companies",
        sa.Column(
            "owner_id",
            sa.Integer(),
            nullable=True
        )
    )

    op.create_foreign_key(
        None,
        "companies",
        "users",
        ["owner_id"],
        ["id"]
    )


#def downgrade() -> None:
    #"""Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'companies', type_='foreignkey')
    #op.drop_column('companies', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint(
        None,
        "companies",
        type_="foreignkey"
    )

    op.drop_column(
        "companies",
        "owner_id"
    )